apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/djw8605/nrp-clickhouse
    newName: ghcr.io/djw8605/nrp-clickhouse
    newTag: latest

patches:
  - path: cronjob-patch.yaml
