---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clickhouse-backup-credentials
  namespace: access-accounting
spec:
  encryptedData:
    password: AgAO+vWvqyWOdxztl+OqnkWfZLvB1/GRwlO/WOu0TPEpqkHjKZAmWe2nJLrKtTrRmSH4npxQmY5DMLPDjDTYc+pzxvc8/U6HxACYrc8KuJO3y6RNUGhFolXMRXQ+xERrl1NaGnWj1Uf3koJGqfg9Ldrd8CumGmqT1DRv4ik/XB1HZSUl9Hekj3UdCG0ur+Mp1Vb2YmD+KflJwBgS0ZFoSj0znEcMRvth/FO+14rEMaULqAx2DAwqo1diPHJaHGYMwMGzKeTWnWS8+R8+qytAaBkCtLp9lH8tNvoD+3ASxIpJudJVmfIqADKvTH7SSkYQdCIDgZYqiUBmiJx2SiMJP6nsgNYwBknphE7gGmLy3ttDOwDl0wMx7G6lcsZ85HupwZfn773xSofOW2Eat03K7qUb2quvE0zszpD3cso7ZVUFTnRXkWWHV/t8NHk4wjt6LjU5VgQULmOOeKFd4gxF5TfEIU4J6B/6J8YXRkRa8P4HDuPm4j7PbJ2hEKvsqWAjyByhLWHH8nx7s6OHpfL2NlU2+tsUohjbFb3kzAsxIxy9Fozk5Dlp55lxxrAvlPV2nTCIvfkAv31iNA8SI10/fxtGKYVfgNYgPkJMHtR4kG7oV9cOhK3jiNZmEFi4tCR8xXdZ67nx1dhiM97H3L6UL4fOBmGN2En75zljqddAWb1/43V/bds0DK3l3anQfwCF4yokvzVvBMnHk9+CAyqeYi8Yup3jvrIngbVZURiqXtY7Iffhh9xkRlLsGerXkTHfvR9ulj9JyFqS1BRbohRXJAlw
  template:
    metadata:
      creationTimestamp: null
      name: clickhouse-backup-credentials
      namespace: access-accounting
    type: Opaque
